### ISSUE TITLE
Conversion failed when converting the varchar value '6.0' to data type int.

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/wcs#34]
https://openfn.org/projects/1168/runs/9902544

**Comment by lakhassane** [comment]
@aleksa-krolls We are attempting to insert data containing a price in the database but it's not possible because from the database perspective price is an integer while it should be a decimal as in the data.

I would recommend modifying that specific column in the DB, rather than altering the data to reduce changes impact.

**Comment by aleksa-krolls** [comment]
@lakhassane Go ahead and make the DB change. FYI, we have the green light to make any DB changes as needed - but good idea to double check with me first :). Thank you!

**Comment by taylordowns2000** [comment]
Change made in the DB. This is fixed.
