### ISSUE TITLE
Upsert Postgres table fails in automation job `02a` when Kobo form cloned

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs#73]
## Issue
A couple of things...
1. Job `automation/02a-syncToPostgres.js` sometimes fails with errors like `error: relation "wcs__formgroup_clonedect1checklistpréparationpiègephotospecie" already exists` when users clone a Kobo form and try to sync it via the automation solutions. 
- See run failure here: https://www.openfn.org/projects/1168/runs/10468696
- And another example: https://www.openfn.org/projects/1168/runs/10468895
2. It doesn't look like prefix `p2` is populating for `FormGroup`. It was set to `Cameratrapping` in this fetch job 00: https://www.openfn.org/projects/1168/jobs/3710
3. Please add the formId or name to the OpenFn run logs wherever possible to make troubleshooting easier! 

@ritazagoni can help troubleshoot if needed. 

## state
See LP for WCS ConSoSoc DB. 
See triggering Kobo form: https://kf.kobotoolbox.org/#/forms/aydKvZSY9kdnDZn6uLvqgZ/summary
This form Id was added to job `00-findUpdates.js`. 

## output
We expect this cloned Kobo form to map to a new Postgres table.

**Comment by lakhassane** [comment]
Feedback on this @aleksa-krolls 
1. Postgres allows a `table_name` to be `63 bytes` at max but in some cases (as this one `wcs__formgroup_clonedect1checklistpréparationpiègephotospecies` (a) ), we have `64 bytes`. 
Thus, postgres automatically remove the last character `s` and create a table as `wcs__formgroup_clonedect1checklistpréparationpiègephotospecie` (b). 

But then, when we re-run, the job will still try to match a table as (a), which it will not found, then it will try to create it, and postgres with truncate again to give us (b)  which brings failure because (b) already exist. Does that make sense? @taylordowns2000 

2. corrected.

**Comment by aleksa-krolls** [comment]
@lakhassane Thanks for this. 

Re: 1 - We need to come up with a new naming convention that will always be under `63 bytes` then. WCS wants to ensure we always keep `p1_p2_formName{someAbbreviated-GroupName}`. So please shorten `GroupName` as needed to ensure we don't exceed 63 bytes. 

Also let's remove the extra underscore `_` between `p1` and `p2` to output --> `wcs_formgroup_clonedect1checklistpréparationpiègephotospecies`.

**Comment by lakhassane** [comment]
RE your question: Yes this is because of the console.logs. I added one console.logs `#L647` before destructuring the value used inside (`fields`) thus the error. This error would pop up each time you were creating a new user

@aleksa-krolls these 2 errors are due to the fact that `Work Email` is null on state. Is this a normal behavior ? If yes, I will add a condition to test if empty. But beware of the fact that if it is null `user principal name` will also be null and I don't know if that is wanted.

**Comment by aleksa-krolls** [comment]
@ritazagoni please test on Monday and close/comment as appropriate :)
