### ISSUE TITLE
Bug: `auto/...{FormName}` job fails if form contains repeat groups

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/wcs#78]
## Describe the issue
When writing Kobo form subsmission data to the database, the automatically generated `auto/...{FormName}` (eg. `auto/WCS_Marche_24novSwmMarcheTest` job fails with error `error: ON CONFLICT DO UPDATE command cannot affect row a second time`. Form data is written to the form table (`wcs_marche_24novswmmarchetest`), but repeat group tables (`wcs_marche_24novswmmarchetestvendor` and `wcs_marche_24novswmmarchetestvendorsales`) are not populated. 

## Expected behavior
When a writing submission data from a form with repeat groups, submission data is written to the form table and repeat group data is written in the repeat group tables. 

## Steps to Reproduce
Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://openfn.org/projects/1168/runs/10569491. Run was triggered by https://openfn.org/projects/1168/messages/10181657.

### expression.js
Link to the job itself: https://openfn.org/projects/1168/jobs/3760

### state.json
Kobo: See LP for openfn_kobo
DB: See LP for WCS ConSoSci DB

## Steps to test the fix/resolve
Configuration on production only contains test data, it is safe to test. If new form or modification needed in Kobo, ping @ritazagoni.

**Comment by aleksa-krolls** [comment]
@lakhassane @ritazagoni The issue here is that in the job, we're are using `upsertMany()` for repeat group records... but assigning the same `GeneratedUuid` to every item in the repeat group. 
`GeneratedUuid: state.data.body._id+'-'+state.data.body._xform_id_string+'-'+2`

This uuid needs to be unique for each item to leverage upserts, which seems impossible to automate. Therefore...
1. `GeneratedUuid` should not have a uniqueness constraint on repeat group tables - rather this is the way to identify which repeat group rows belong to which Kobo submission. 
2. Then let's leverage `insertMany()` for uploading repeat group rows of data.
3. And then every time the job runs, OpenFn should delete any existing repeat group data before executing the `insertMany()` operation to ensure this data is overwritten. See what we do in BNS: https://github.com/OpenFn/wcs/blob/master/bns/price.js#L41-L46

I thought this was the agreed approach for repeat groups... is there a reason for switching to `upsertMany()` from `insertMany()` that I'm missing? cc @taylordowns2000

**Comment by taylordowns2000** [comment]
Hey @lakhassane , what's the status here? I liked that idea we talked through earlier today.
